### ISSUE TITLE
no such file or directory Error

### ISSUE THREAD

**Issue by derbra1513** [davidhauck/SeatsAeroFinder#1]
Getting the following error when running the provided example code "npm run explore -- --from ord --class F J -d --exclude-regions "North America" -n 2"

Finished reading stored db  2 ms
refreshing source:  lifemiles
[Error: ENOENT: no such file or directory, open '/Users/------/SeatsAeroFinder/.lifemiles.json.tmp'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/------/SeatsAeroFinder/.lifemiles.json.tmp'
}

**Comment by davidhauck** [comment]
This was due to the default directory not existing. I've updated the code to create the directory if it does not exist. c6ed2e1a06bd118857db56c7e6fbaad106c84610
